services:
  gateway:
    image: gheo43dn/gateway:latest
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      SERVER_URL: http://api.proptintel.id.vn
    depends_on:
      - auth-service
    restart: always

  auth-service:
    image: gheo43dn/auth-service:latest
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    environment:
      PORT: 4001
      DATABASE_URL: "mysql://root:sum2530623306@real-estate-backend-mysql-1:3306/mysql_db"
      GOOGLE_CLIENT_ID: 893629871972-p0g15vvj9pu5a83fghp5jurk2m0cs8fb.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: http://api.propintel.id.vn/auth/google/callback
    restart: always
  
  property-service:
    image: gheo43dn/property-service:latest
    ports:
      - "4002:4002"
    depends_on:
      - mysql
    environment:
      PORT: 4002
      DATABASE_URL: "mysql://root:sum2530623306@real-estate-backend-mysql-1:3306/properties_db"
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sum2530623306
      MYSQL_DATABASE: mysql_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - gateway

volumes:
  mysql-data:
