version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    image: gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    environment:
      PORT: 4000
      SERVER_URL: https://api.propintel.id.vn

  auth-service:
    build:
      context: ./services/auth-service
    image: auth-service
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    environment:
      PORT: 4001
      DATABASE_URL: "mysql://root:sum2530623306@mysql:3306/mysql_db"
      GOOGLE_CLIENT_ID: 893629871972-p0g15vvj9pu5a83fghp5jurk2m0cs8fb.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: https://api.propintel.id.vn/auth/google/callback

  property-service:
    build:
      context: ./services/property-service
    image: property-service
    ports:
      - "4002:4002"
    depends_on:
      - mysql
    environment:
      PORT: 4002
      DATABASE_URL: "mysql://root:sum2530623306@mysql:3306/mysql_db"
  
  mail-service:
    build:
      context: ./services/mail-service
    image: mail-service
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
      MAIL_USER: realestate14052025@gmail.com
      MAIL_PASS: lbjv ijzq wfzy jhxk
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: sum2530623306
      MYSQL_DATABASE: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
