services:
  gateway:
    image: gheo43dn/gateway:latest
    ports:
      - "4000:4000"
    environment:
      AUTH_SERVICE: http://auth-service:4001
    depends_on:
      - auth-service
    restart: always

  auth-service:
    image: gheo43dn/auth-service:latest
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sum2530623306
      MYSQL_DATABASE: mysql_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
