version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "4000:4000"
    volumes:
      - ./gateway:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE: http://auth-service:4001
      
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "4001:4001"
    volumes:
      - ./services/auth-service:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: sum2530623306
      MYSQL_DATABASE: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
