version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    image: gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE: http://auth-service:4001

  auth-service:
    build:
      context: ./services/auth-service
    image: auth-service
    ports:
      - "4001:4001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: sum2530623306
      DB_NAME: mysql_db

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: sum2530623306
      MYSQL_DATABASE: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
